name: visuaudio

dependencies:
  - defaults::python
  - defaults::line_profiler
  - defaults::memory_profiler
  - defaults::matplotlib
  - defaults::numba
  - defaults::numpy
  - defaults::pyopengl
  - defaults::pyqt
  - defaults::pyqtgraph
  - defaults::scipy
  - conda-forge::python-sounddevice
